
const NOTETYPE_TAP = 0;
const NOTETYPE_LONGSTART = 1;
const NOTETYPE_LONGEND = 1;
const NOTETYPE_FLICK = 2;
const NOTETYPE_KEEP2FLICK = 3;
const NOTETYPE_FLICKINKEEP = 4;
const NOTETYPE_LONGFLICKSTART = 5;

const NOTEVIEW_TAP = 0;
const NOTEVIEW_LONG = 1;
const NOTEVIEW_FLICK = 2;

const FLICK_BOTH = 0;
const FLICK_LEFT = 1;
const FLICK_RIGHT = 2;
